replicaCount: 1

envVars:
  - name: ENV
    value: dev
  - name: DB_HOST
    value: postgres-dev.postgres.svc.cluster.local
  - name: DB_PORT
    value: 5432
image:
  repository: 793414601893.dkr.ecr.us-east-1.amazonaws.com/backoffice-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort     # <<< สำคัญ: ตั้งให้เป็น NodePort
  port: 80
  targetPort: 3000   # <<< แก้ให้ตรงกับ port ที่ container ใช้
  nodePort: 32080    # <<< จะใช้พอร์ตนี้ในการ reverse จาก NGINX

resources: {}
