apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backoffice-api
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: backoffice-api
            valuesFile: dev.yaml
          - env: prod
            namespace: backoffice-api-prod
            valuesFile: prod.yaml
          - env: staging
            namespace: backoffice-api-staging
            valuesFile: staging.yaml
  template:
    metadata:
      name: '{{env}}-backoffice-api'
    spec:
      project: default
      source:
        repoURL: https://github.com/demo-argocd-application/application-argocd.git
        targetRevision: HEAD
        path: backoffice-api
        helm:
          valueFiles:
            - values.yaml
            - '{{valuesFile}}'       # <<<<<< ดึงไฟล์แต่ละ env แบบ dynamic
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
