apiVersion: v1
kind: Service
metadata:
  name: {{ include "backoffice-api.fullname" . }}
  labels:
    {{- include "backoffice-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .containerPort }}
    {{- end }}
  selector:
    {{- include "backoffice-api.selectorLabels" . | nindent 4 }}
