apiVersion: v1
kind: Service
metadata:
  name: {{ include "backoffice-api.fullname" . }}
  labels:
    {{- include "backoffice-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "backoffice-api.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort | default nil }}
